name: cache built assets
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # use a third-party action to check out the repo
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: public
          key: cache-public-${{ hashFiles('public/**/*') }}

      - uses: actions/cache@v2
        with:
          path: .cache
          key: cache-cache-${{ hashFiles('.cache/**/*') }}

      - run: npm i

      - run: npm run build

      - name: deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        run: npx netlify-cli deploy --dir=public --prod
